/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'emerald-deep': '#0B4A2E',
        'emerald-leaf': '#1E7A42',
        'emerald-leaf-soft': '#2C8F52',
        'gold': '#D9A62B',
        'gold-soft': '#F0D68A',
        'ivory': '#F7F4EC',
        'ivory-2': '#FBF9F3',
        'ink': '#12261B',
        'ink-soft': '#3E5548',
        'border': '#DCD6C5',
      },
      fontFamily: {
        serif: ['"Playfair Display"', '"Times New Roman"', 'Times', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        heading: ['"Playfair Display"', '"Times New Roman"', 'Times', 'serif'],
        body: ['"Plus Jakarta Sans"', 'sans-serif'],
        'display-lg': ['"Playfair Display"', '"Times New Roman"', 'Times', 'serif'],
        'headline-lg': ['"Playfair Display"', '"Times New Roman"', 'Times', 'serif'],
        'headline-md': ['"Playfair Display"', '"Times New Roman"', 'Times', 'serif'],
        'headline-sm': ['"Playfair Display"', '"Times New Roman"', 'Times', 'serif'],
        'body-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-md': ['"Plus Jakarta Sans"', 'sans-serif'],
        'body-sm': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'label-md': ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['3.5rem', { lineHeight: '4rem', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-lg-mobile': ['2rem', { lineHeight: '2.5rem', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-lg': ['0.875rem', { lineHeight: '1.25rem', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-md': ['0.75rem', { lineHeight: '1rem', letterSpacing: '0.02em', fontWeight: '600' }],
        'body-md': ['1rem', { lineHeight: '1.5rem', fontWeight: '400' }],
        'body-lg': ['1.125rem', { lineHeight: '1.75rem', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.375rem', fontWeight: '400' }],
        'headline-sm': ['1.25rem', { lineHeight: '1.75rem', fontWeight: '600' }],
        'headline-lg': ['2.5rem', { lineHeight: '3rem', letterSpacing: '-0.015em', fontWeight: '600' }],
        'headline-md': ['1.75rem', { lineHeight: '2.25rem', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'margin': '3rem',
        'margin-mobile': '1.25rem',
        'gutter': '1.5rem',
        'gutter-mobile': '1rem',
      },
    },
  },
  plugins: [],
}
